
 const products = 
 [
   {
    "PK": "product",
    "SK": "0001",
    "type": "product",
    "name": "T-shirt with Tape Details",
    "price": 120,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "uni",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0002",
    "type": "product",
    "name": "Skinny Fit Jeans",
    "price": 260,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 20,
    "style": "casual",
    "gender": "uni",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0003",
    "type": "product",
    "name": "Checkered Shirt",
    "price": 180,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0004",
    "type": "product",
    "name": "Sleeve Striped T-shirt",
    "price": 160,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 30,
    "style": "casual",
    "gender": "women",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0005",
    "type": "product",
    "name": "Vertical Striped Shirt",
    "price": 232,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 20,
    "style": "casual",
    "gender": "women",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0006",
    "type": "product",
    "name": "Courage Graphic T-shirt",
    "price": 145,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0007",
    "type": "product",
    "name": "Loose Fit Bermuda Shorts",
    "price": 80,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "women",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0008",
    "type": "product",
    "name": "Faded Skinny Jeans",
    "price": 210,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "women",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0009",
    "type": "product",
    "name": "One Life Graphic T-shirt",
    "price": 300,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 40,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0010",
    "type": "product",
    "name": "Polo with Contrast Trims",
    "price": 242,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 20,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0011",
    "type": "product",
    "name": "Gradient Graphic T-shirt",
    "price": 145,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "women",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0012",
    "type": "product",
    "name": "Polo with Tipping Details",
    "price": 180,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 0,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   },
   {
    "PK": "product",
    "SK": "0013",
    "type": "product",
    "name": "Black Striped T-shirt",
    "price": 150,
    "description": "Lorem Ipsum",
    "xxs": 3,
    "xs": 3,
    "s": 3,
    "m": 3,
    "l": 3,
    "xl": 3,
    "xxl": 3,
    "3xl": 3,
    "4xl": 3,
    "color": "[red, blue, green, yellow]",
    "discount": 30,
    "style": "casual",
    "gender": "men",
    "imageurl": "https:\/\/picsum.photos\/200"
   }
  ]

   export { 
    products
   }